# Generated by Django 3.2.16 on 2022-11-29 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HouseOwnerApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookingstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wastecollector_id', models.IntegerField()),
                ('status', models.CharField(max_length=200)),
                ('collected_date', models.DateField()),
                ('slot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HouseOwnerApp.slotbooking')),
            ],
        ),
    ]
